// == PART 1 ==

function part1(input: string): number {
  let grid = input.replace("S", "|").split("\n").map(line => [...line]);

  for (let row = 1; row < grid.length; row++) {
    grid[row] = grid[row].map((cell, col) => {
      if (cell === "." && grid[row - 1][col] === "|") return "|";
      if (grid[row][col + 1] === "^" && grid[row - 1][col + 1] === "|") return "|";
      if (grid[row][col - 1] === "^" && grid[row - 1][col - 1] === "|") return "|";
      return cell;
    });
  }

  return grid.reduce((splits, line, row) => splits + line.filter((cell, col) => cell === "^" && grid[row - 1][col] === "|").length, 0)
}

// == PART 2 ==

function part2(input: string): number {
  let grid = input.split("\n").map(line => [...line].map<"^" | number>(cell => cell === "^" ? "^" : cell === "S" ? 1 : 0));
  let timelines = grid.shift() as number[]; 

  for (let line of grid) {
    timelines = line.map((cell, col) => {
      if (cell === "^") return 0;
      let timelinesFromLeft = line[col - 1] === "^" ? timelines[col - 1] : 0;
      let timelimesFromTop = timelines[col];
      let timelinesFromRight = line[col + 1] === "^" ? timelines[col + 1] : 0;
      return timelinesFromLeft + timelimesFromTop + timelinesFromRight;
    });
  }

  return timelines.reduce((sum, count) => sum + count, 0);
}

// == ASSERTS ==

console.assert(part1(`\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`) === 21);

console.assert(part2(`\
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`) === 40);
