// == TYPES ==

interface Position {
  row: number;
  col: number;
}

// == SHARED ==

function getAntennas(grid: string[][]): Record<string, Position[]> {
  return grid.reduce<Record<string, Position[]>>((antennas, line, row) => {
    line.forEach((cell, col) => {
      if (cell === ".") return;
      antennas[cell] = antennas[cell] ?? []
      antennas[cell].push({row, col});
    });
    return antennas;
  }, {});
}

// == PART 1 ==

function part1(input: string): number {
  let grid = input.split("\n").map(line => [...line]);

  let maxRow = grid.length - 1;
  let maxCol = grid[0].length - 1;
  let antennas = getAntennas(grid);
  let antinodes = new Set<string>();

  Object.values(antennas).forEach(sameFrequencyAntennas => {
    sameFrequencyAntennas.forEach((antenna1, index) => {
      sameFrequencyAntennas.slice(index + 1).forEach(antenna2 => {
        let rowDiff = antenna1.row - antenna2.row;
        let colDiff = antenna1.col - antenna2.col;

        [
          {row: antenna1.row + rowDiff, col: antenna1.col + colDiff},
          {row: antenna2.row - rowDiff, col: antenna2.col - colDiff},
        ]
          .filter(({row, col}) => row >= 0 && row <= maxRow && col >= 0 && col <= maxCol)
          .forEach(({row, col}) => antinodes.add(`${row},${col}`));
      });
    });
  });

  return antinodes.size;
}

// == PART 2 ==

function part2(input: string): number {
  let grid = input.split("\n").map(line => [...line]);

  let maxRow = grid.length - 1;
  let maxCol = grid[0].length - 1;
  let antennas = getAntennas(grid);
  let antinodes = new Set<string>();

  Object.values(antennas).forEach(sameFrequencyAntennas => {
    sameFrequencyAntennas.forEach((antenna1, index) => {
      sameFrequencyAntennas.slice(index + 1).forEach(antenna2 => {
        let rowDiff = antenna1.row - antenna2.row;
        let colDiff = antenna1.col - antenna2.col;

        for (
          let {row, col} = antenna1;
          row >= 0 && row <= maxRow && col >= 0 && col <= maxCol;
          row += rowDiff, col += colDiff
        ) {
          antinodes.add(`${row},${col}`);
        }

        for (
          let {row, col} = antenna2;
          row >= 0 && row <= maxRow && col >= 0 && col <= maxCol;
          row -= rowDiff, col -= colDiff
        ) {
          antinodes.add(`${row},${col}`);
        }
      });
    });
  });

  return antinodes.size;
}

// == ASSERTS ==

console.assert(part1(`\
..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........`) === 2);
console.assert(part1(`\
..........
..........
..........
....a.....
........a.
.....a....
..........
..........
..........
..........`) === 4);
console.assert(part1(`\
..........
..........
..........
....a.....
........a.
.....a....
..........
......A...
..........
..........`) === 4);
console.assert(part1(`\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`) === 14);

console.assert(part2(`\
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`) === 9);
console.assert(part2(`\
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`) === 34);
